// //// AUTH
export const DARKMODE_CONFIG = 'DARKMODE_CONFIG'
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_LOADED = 'AUTH_LOADED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
// //// END-AUTH
// //// BARANG
export const BARANG_LOADING = 'BARANG_LOADING'
export const BARANG_LOADED = 'AUTH_LOADED'
export const TABLE_BARANG_LOADED = 'TABLE_BARANG_LOADED'
// //// END-BARANG
