////// AUTH
export const CREATE_SUPER_USER_SUCCESS = 'CREATE_SUPER_USER_SUCCESS'
export const DARKMODE_CONFIG = 'DARKMODE_CONFIG'
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_LOADED = 'AUTH_LOADED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USER_LOADED = 'USER_LOADED'
export const USER_EXPIRED = 'USER_EXPIRED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
////// END-AUTH
////// END-ACCOUNT
export const ACCOUNT_LOADING = 'ACCOUNT_LOADING'
export const ACCOUNT_LOADED = 'ACCOUNT_LOADED'
export const GET_ACCOUNT_ID_FOR_DETAIL = 'GET_ACCOUNT_ID_FOR_DETAIL'
export const ACCOUNT_DETAIL = 'ACCOUNT_DETAIL'
export const GET_ACCOUNT_ID_FOR_UPDATE = 'GET_ACCOUNT_ID_FOR_UPDATE'
export const LIST_ACCOUNT = 'LIST_ACCOUNT'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'
export const TOKO_DETAIL = 'TOKO_DETAIL'
////// END-ACCOUNT
////// TRANSAKSI
export const TRANSAKSI_LOADING = 'TRANSAKSI_LOADING'
export const TRANSAKSI_LOADED = 'TRANSAKSI_LOADED'
export const ADD_BARANG_TO_TRANSAKSI = 'ADD_BARANG_TO_TRANSAKSI'
export const CHANGE_TRANSAKSI_ITEM_JUMLAH = 'CHANGE_TRANSAKSI_ITEM_JUMLAH'
export const CLEAR_BARANG_IN_TRANSAKSI = 'CLEAR_BARANG_IN_TRANSAKSI'
export const CLEAR_A_BARANG_FROM_TRANSAKSI = 'CLEAR_A_BARANG_FROM_TRANSAKSI'
////// END-TRANSAKSI
////// JENISBARANG
export const JENISBARANG_LOADING = 'JENISBARANG_LOADING'
export const JENISBARANG_LOADED = 'JENISBARANG_LOADED'
export const GET_JENISBARANG_ID_FOR_DETAIL = 'GET_JENISBARANG_ID_FOR_DETAIL'
export const JENISBARANG_DETAIL = 'JENISBARANG_DETAIL'
export const GET_JENISBARANG_ID_FOR_UPDATE = 'GET_JENISBARANG_ID_FOR_UPDATE'
export const JENISBARANG_DELETED = 'JENISBARANG_DELETED'
export const LIST_JENISBARANG = 'LIST_JENISBARANG'
////// END-JENISBARANG
////// BARANG
export const BARANG_LOADING = 'BARANG_LOADING'
export const BARANG_LOADED = 'BARANG_LOADED'
export const TABLE_BARANG_LOADED = 'TABLE_BARANG_LOADED'
////// END-BARANG
////// MESSAGES
export const SUCCESS_MESSAGES = 'SUCCESS_MESSAGES'
export const INFO_MESSAGES = 'INFO_MESSAGES'
export const WARNING_MESSAGES = 'WARNING_MESSAGES'
export const ERROR_MESSAGES = 'ERROR_MESSAGES'
export const CLEAN_MESSAGES = 'CLEAN_MESSAGES'
////// END-MESSAGES