// //// AUTH
export const DARKMODE_CONFIG = 'DARKMODE_CONFIG'
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_LOADED = 'AUTH_LOADED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
// //// END-AUTH
// //// TRANSAKSI
export const TRANSAKSI_LOADING = 'TRANSAKSI_LOADING'
export const TRANSAKSI_LOADED = 'TRANSAKSI_LOADED'
export const ADD_BARANG_TO_TRANSAKSI = 'ADD_BARANG_TO_TRANSAKSI'
export const CHANGE_TRANSAKSI_ITEM_JUMLAH = 'CHANGE_TRANSAKSI_ITEM_JUMLAH'
export const CLEAR_BARANG_IN_TRANSAKSI = 'CLEAR_BARANG_IN_TRANSAKSI'
export const CLEAR_A_BARANG_FROM_TRANSAKSI = 'CLEAR_A_BARANG_FROM_TRANSAKSI'
// //// END-TRANSAKSI
// //// BARANG
export const BARANG_LOADING = 'BARANG_LOADING'
export const BARANG_LOADED = 'BARANG_LOADED'
export const TABLE_BARANG_LOADED = 'TABLE_BARANG_LOADED'
// //// END-BARANG
